name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 3. Cache npm dependencies
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}

      # OPTIMIZATION
      # - name: Setup Node.js with cache
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 18
      #     cache: 'npm'

      # 4. Install dependencies
      - name: Install dependencies
        run: npm install
        
      # Advance Caching
      # - uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: false
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
          
      - name: Build Docker Image
        run: DOCKER_BUILDKIT=1 docker build -t myapp:latest .
  
      # 5. Run tests
      # - name: Run tests
      #   run: npm test

      - name: Build Code
        run: npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: dist/
    
