name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. Cache npm dependencies
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # OPTIMIZATION
      # - name: Setup Node.js with cache
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 18
      #     cache: 'npm'

      # 4. Install dependencies
      - name: Install dependencies
        run: npm install

      # 5. Run tests
      - name: Run tests
        run: npm test